site_name: "Language and Logic"
site_description: "Language and Logic"
site_url: https://llmsci.github.io/language-and-logic/
repo_url: https://github.com/llmsci/language-and-logic

docs_dir: docs_temp

theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - tables
  - admonition

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Sets: sets/sets.md
  - Boolean Algebra: bool/bool.md
  - Logic Gates: logic-gates/logic-gate.md
  - Logical Operators: logic-operators/logic-operators.md
